[package]
name = "toy_abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
itertools = "0.11.0"
ola-lang-abi = "1.0.1"
regex = "1.10.2"
serde_json = "1.0.108"
